### ISSUE TITLE
SSL certificate for the .org domain

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#27]
**Is your feature request related to a problem? Please describe.**
The site should work on HTTPS protocol.

**Describe the solution you'd like**
Check if we already have some certificates.
If no, change domain settings (who owner?) to the simplest GitHub way and use a free version of Let's Encrypt cert.

**Comment by voborgus** [comment]
@cewilliams can put some details here, please?

**Comment by cewilliams** [comment]
Current certs are through GitHub, since the hosting is done with GH Pages. https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain has more information. 

We currently have `Enforce HTTPS` turned on for this domain.

**Comment by voborgus** [comment]
Are you talking about the main site [http://innersourcecommons.org/](http://innersourcecommons.org/)? I see plain HTTP there, and the goal is to have HTTPS with cert when we'll move to the main domain.

**Comment by voborgus** [comment]
@lenucksi need your help here

**Comment by lenucksi** [comment]
Don't know how I could help here. DNS and domain management is completely with @cewilliams. 
What do you think I can do here? (Maybe I can?)

**Comment by cewilliams** [comment]
@voborgus : My apologies, I was looking at the settings for .net, not .org. I have turned on Enforce HTTPS on .org as well now.

The certificate(s) are from Let's Encrypt, but they are managed entirely by GitHub (since they are also providing the webserver). GitHub requests the certificates, installs them when they are generated, and rotates them before they expire. We don't have to do anything for them, other than use the gh-pages config in the repo settings.

**Comment by voborgus** [comment]
Awesome! Thanks a lot.
