### ISSUE TITLE
Ensure the Patterns Working Group ok to go live

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.net#70]
**Is your feature request related to a problem? Please describe.**
We need to have a green light from the Patterns working group on their section for moving the current site to production.

**Describe the solution you'd like**
Ask approvement. Can be connected with #47

**Comment by claredillon** [comment]
What's required to close this? 

Currently points to Patterns GitHub repo, as it has done in the previous site. @spier - what else do you think is necessary for MVP?

**Comment by spier** [comment]
We can close this issue here.
The MVP-work for the Patterns WG is in #47.

**Comment by voborgus** [comment]
Should we wait for #47 issue completion before the closing this?

**Comment by spier** [comment]
Actually ... I reconsidered. Yeah, let's keep this issue open, just as a reminder.

Once we have the new site it a pretty stable state we can ask in the patterns WG what they think about the new page from a "patterns perspective" :) I don't expect much feedback or requests for radical changes there though because the old site had very little pattern-specific content.

Still worthwhile asking though.

**Comment by spier** [comment]
I think the most important Pattern-related content is ported to the new site now.

To confirm that with the rest of the Pattern-lovers, I have asked all of them to review the new site (see [slack thread](https://innersourcecommons.slack.com/archives/C2EFRTS6A/p1614620445047900)).

Let's give this a couple of days. If we don't get any major feedback then we can consider this issue closed.

**Comment by spier** [comment]
We got one response to the slack thread (link above), and that was positive.
So I would think that we are good to go ahead with this!
